### ISSUE TITLE
Selección de plantilla

### ISSUE THREAD

**Issue by igomezal** [igomezal/MultimediaPracticaFinal#2]

**Comment by igomezal** [comment]
Selección de plantilla base para el proyecto

**Comment by sergioserr** [comment]
Opción 1: [Template](http://www.free-css.com/free-css-templates/page183/marathon)

**Comment by Alvaro95pa** [comment]
Opción 2: [BLUE template](http://www.free-css.com/free-css-templates/page202/blue)

**Comment by igomezal** [comment]
PLANTILLA [BLUE Template](http://www.free-css.com/free-css-templates/page202/blue)
