### ISSUE TITLE
Selección de logo de la página

### ISSUE THREAD

**Issue by sergioserr** [igomezal/MultimediaPracticaFinal#4]
Selección del logo base para el proyecto

**Comment by Alvaro95pa** [comment]
El logo consistirá en un chicharro (pez).
Algo similar a la conocida [representación tinerfeña de este pez](https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/El_Chicharro_01.jpg/1200px-El_Chicharro_01.jpg).
