### ISSUE TITLE
Reunión 5/04/2017

### ISSUE THREAD

**Issue by Alvaro95pa** [igomezal/MultimediaPracticaFinal#5]
Temas discutidos:

- [x] Usar aria
- [x] Validar vídeo presentación (index.html) <- No habíamos pasado este video a Galería? <- Pasado a galería
- [x] Foco de teclado visible al tabular
- [x] Menú dropdown con animación
- [x] Pruebas en navegadores  (Mozilla, Chrome, Edge, Opera, Explorer...)
- [x] Formulario de envío de postal
- [x] Recomendaciones/Noticias -> Con recomendación/noticia concreta
- [x] Posicionamiento web -> Tittle y meta="description" en head 
- [x]  Plugin Google Analytics
- [x] Footer -> Añadir sitemap
- [x] Logo escultura chicharro -> Gimp

**Comment by Alvaro95pa** [comment]
Tareas realizadas y en revisión:

- Logo e icono añadidos -> Revisar si la estética resulta adecuada
- Metainf con descripción y con keywords añadida -> Revisar si el contenido es adecuado

**Comment by igomezal** [comment]
- Añadido video de presentación (se puede ajustar un poco más el margen)
- Foco visible (comentando del css los estilos con :focus)
- Añadido aria al menú (tabindex)
- Rutas de las imagenes cambiadas de ../img/ a img/

**Comment by Alvaro95pa** [comment]
- Menú dropdown añadido en interes.html (anteriormente contacto.html)
